
# Tips for generating origin destination data:

- Voor de (eenvoudige) modellering van verkeer van en naar steden en dorpen:
- + Gegevens over het aantal inwoners en het percentage werkenden, adv. regionale kerncijfers op StatLine.
- + Inzichten uit de graviteitstheorie: bijvoorbeeld aannemen dat 
- + 1) het verkeer tussen twee steden evenredig toeneemt met de grootte van de (beroeps)bevolking van de steden, 
- + 2) en omgekeerd evenredig is met het kwadraat van de afstand (of reistijd) tussen de steden.
- + Inzichten uit de literatuur over verkeer en vervoer. In ‘Verkeer en vervoer in hoofdlijnen’ staat bijvoorbeeld dat Schafer (1998) concludeert dat het reistijdbudget wereldwijd gemiddeld op 1,1 uur per persoon per dag ligt, ongeacht de economische, sociale en geografische situatie.

- Resultaten van het Onderzoek Verkeer in Nederland (OViN). 
- + Bijvoorbeeld: http://statline.cbs.nl/Statweb/publication/?VW=T&DM=SLNL&PA=83494NED&D1=0-2&D2=0&D3=1-8&D4=1-14&D5=0&D6=l&HD=170301-1558&HDR=T,G5,G2&STB=G1,G3,G4
- + Het model zou kunnen worden geijkt met behulp van verkeersmetingen, bijvoorbeeld met het aantal voertuigpassages op de snelwegen. 
- Zie: http://statline.cbs.nl/Statweb/publication/?DM=SLNL&PA=82855NED&D1=0&D2=0,195-239&D3=39-51&VW=T

- De statistiek Nabijheid Voorzieningen: http://statline.cbs.nl/Statweb/publication/?DM=SLNL&PA=80305NED&D1=0,19,23,35,47-50,85,109&D2=0,76,357-358,435&D3=7-9&VW=T

- De combinatie van traffic demand data en metingen op de wegen is al eens theoretisch uitgewerkt door Yinyi Ma. Zie haar proefschrift: https://repub.eur.nl/pub/80174

- Info over graviteitsmodellering:
- + Eenvoudige omschrijving: https://nl.wikipedia.org/wiki/Graviteitsmodel_in_de_geografie
- + Gedetailleerde uitwerking: http://www.kuleuven.be/traffic/dwn/H111part1.pdf

- Search on: ‘traffic demand modelling’

- Info on mobility:
- https://www.kimnet.nl/
- https://www.cbs.nl/nl-nl/publicatie/2016/25/transport-en-mobiliteit-2016


 
# Generating commutes dataset based on the gravity based model 

- calculate the distances between all points (cities) in a dataset (so in 5 rows, (n-1)+(n-2)+...+(n-n)) 10 total distances)

- calculate the product of the populations of those cities

- calculate the gravity

- determine direction of movement (simple check of larger population of the two compared cities)



# draft setup:

    f <- read.table(header=T, text="     location   population
    1    10,10     1000
    2    20,20     2000 
    3    30,30     3000
    4    40,40     4000
    5    50,50     5000", stringsAsFactors=F)

    locs <- do.call(rbind, lapply(strsplit(df$location,",",T), as.integer))
    (idx <- combn(1:nrow(locs), 2))
    #      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
    # [1,]    1    1    1    1    2    2    2    3    3     4
    # [2,]    2    3    4    5    3    4    5    4    5     5

    (distance <- geosphere::distHaversine(locs[idx[1,],], locs[idx[2,],]) )
    # [1] 1546488 3044009 4463588 5770107 1500779 2930665 4260187 1436941 2785801 1360777

    (popProd <- df$population[idx[1,]]*df$population[idx[2,]])
     # [1]  2000000  3000000  4000000  5000000  6000000  8000000 10000000 12000000 15000000 20000000
 
 

 
 


